language: bash
sudo: false 
dist: trusty
install: gem install bashcov
addons:
  apt:
    packages:
    - sqlite3
    - shunit2
    - shellcheck
    - rustc
script:
 - curl -skOL https://raw.githubusercontent.com/anordal/shellharden/master/shellharden.rs && rustc shellharden.rs
 - export PATH=".:$PATH"
 - make test
